platform :ios, '10.0'

node_modules_path = '../node_modules'
root_node_modules_path = '../../node_modules'
require_relative "#{node_modules_path}/react-native/scripts/react_native_pods"
require_relative "#{node_modules_path}/@react-native-community/cli-platform-ios/native_modules"

target 'example' do
  config = use_native_modules! 
  
  use_react_native!(:path => config["reactNativePath"])
  
  # Want to install the pod from the source directory so we can change it while developing
  pod 'RNSpotifyRemote', :path => "../../"

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  # Need to specify flipper versions due to issue with XCode 12.5
  # See https://github.com/facebook/flipper/issues/2215#issuecomment-828837100
  use_flipper!({ 'Flipper-Folly' => '2.5.3', 'Flipper' => '0.87.0', 'Flipper-RSocket' => '1.3.1' })
  post_install do |installer|
    flipper_post_install(installer)
  end
end