platform :ios, '10.0'

node_modules_path = '../node_modules'
require_relative "#{node_modules_path}/react-native/scripts/react_native_pods"
require_relative "#{node_modules_path}/@react-native-community/cli-platform-ios/native_modules"

target 'example' do
  config = use_native_modules! 
  
  use_react_native!(:path => config["reactNativePath"])
  
  # RNEventEmitter doesn't seem to support the auto detection, manually specifying instead
  pod 'RNEventEmitter', :path => "#{node_modules_path}/react-native-events"

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end